/**
 * Old Brush · Auckland suburbs and localities
 *
 * Source: English Wikipedia, "List of suburbs of Auckland" (the 187
 * suburbs inside the metropolitan urban limits, which carry an `area`)
 * merged with the Auckland Region locality categories (Rodney, Franklin,
 * Hibiscus Coast, Matakana Coast, Pōhutukawa Coast, Waiheke and the Gulf
 * islands), fetched 2026-09-12.
 *
 * This is a convenience list for the quote flow's suburb autocomplete —
 * it is NOT an authoritative gazetteer and it is not exhaustive. The
 * field always accepts free text, so an unlisted locality never blocks
 * an enquiry. If an exhaustive list is ever needed, replace this file
 * with the LINZ NZ Place Names Gazetteer extract.
 *
 * Macrons are preserved as spelled by the source; `normaliseSuburb`
 * strips them so "Otahuhu" still matches "Ōtāhuhu".
 */

export type Suburb = {
  name: string
  /** Broad part of Auckland — only known for metropolitan suburbs. */
  area?: string
}

export const aucklandSuburbs: readonly Suburb[] = [
  { name: "Ahuroa" },
  { name: "Airport Oaks", area: "South Auckland" },
  { name: "Albany", area: "North Shore" },
  { name: "Alfriston", area: "South Auckland" },
  { name: "Algies Bay" },
  { name: "Ararimu" },
  { name: "Arch Hill", area: "Central Auckland" },
  { name: "Ardmore" },
  { name: "Arkles Bay" },
  { name: "Army Bay" },
  { name: "Auckland City Centre", area: "Central Auckland" },
  { name: "Avondale", area: "West Auckland" },
  { name: "Awana Bay" },
  { name: "Awhitu" },
  { name: "Baddeleys Beach" },
  { name: "Balmoral", area: "Central Auckland" },
  { name: "Bayswater", area: "North Shore" },
  { name: "Bayview", area: "North Shore" },
  { name: "Beach Haven", area: "North Shore" },
  { name: "Beachlands" },
  { name: "Belmont", area: "North Shore" },
  { name: "Big Manly Beach" },
  { name: "Big Ōmaha" },
  { name: "Birkdale", area: "North Shore" },
  { name: "Birkenhead", area: "North Shore" },
  { name: "Blackpool" },
  { name: "Blockhouse Bay", area: "West Auckland" },
  { name: "Bombay" },
  { name: "Botany", area: "East Auckland" },
  { name: "Botany Downs", area: "East Auckland" },
  { name: "Brookby" },
  { name: "Browns Bay", area: "East Coast Bays" },
  { name: "Buckland" },
  { name: "Bucklands Beach", area: "East Auckland" },
  { name: "Buckleton Beach" },
  { name: "Burswood", area: "East Auckland" },
  { name: "Campbells Bay", area: "East Coast Bays" },
  { name: "Campbells Beach" },
  { name: "Castor Bay", area: "North Shore" },
  { name: "Chapel Downs", area: "East Auckland" },
  { name: "Chatswood", area: "North Shore" },
  { name: "Claris" },
  { name: "Clarks Beach" },
  { name: "Clendon Park", area: "South Auckland" },
  { name: "Clevedon" },
  { name: "Clover Park", area: "South Auckland" },
  { name: "Coatesville" },
  { name: "Cockle Bay", area: "East Auckland" },
  { name: "Conifer Grove", area: "South Auckland" },
  { name: "Cornwallis" },
  { name: "Dairy Flat" },
  { name: "Dannemora", area: "East Auckland" },
  { name: "Devonport", area: "North Shore" },
  { name: "Dome Valley" },
  { name: "Drury", area: "South Auckland" },
  { name: "East Tāmaki", area: "East Auckland" },
  { name: "East Tāmaki Heights", area: "East Auckland" },
  { name: "Eastern Beach", area: "East Auckland" },
  { name: "Eden Terrace", area: "Central Auckland" },
  { name: "Ellerslie", area: "Central Auckland" },
  { name: "Epsom", area: "Central Auckland" },
  { name: "Fairview Heights", area: "North Shore" },
  { name: "Farm Cove", area: "East Auckland" },
  { name: "Favona", area: "South Auckland" },
  { name: "Flat Bush", area: "East Auckland" },
  { name: "Forrest Hill", area: "North Shore" },
  { name: "Freemans Bay", area: "Central Auckland" },
  { name: "Glen Eden", area: "West Auckland" },
  { name: "Glen Innes", area: "Central Auckland" },
  { name: "Glenbrook" },
  { name: "Glenbrook Beach" },
  { name: "Glendene", area: "West Auckland" },
  { name: "Glendowie", area: "Central Auckland" },
  { name: "Glenfield", area: "North Shore" },
  { name: "Glorit" },
  { name: "Golflands", area: "East Auckland" },
  { name: "Goodwood Heights", area: "South Auckland" },
  { name: "Grafton", area: "Central Auckland" },
  { name: "Grahams Beach" },
  { name: "Green Bay", area: "West Auckland" },
  { name: "Greenhithe", area: "North Shore" },
  { name: "Greenlane", area: "Central Auckland" },
  { name: "Grey Lynn", area: "Central Auckland" },
  { name: "Half Moon Bay", area: "East Auckland" },
  { name: "Hatfields Beach" },
  { name: "Hauraki", area: "North Shore" },
  { name: "Helensville" },
  { name: "Henderson", area: "West Auckland" },
  { name: "Henderson Valley", area: "West Auckland" },
  { name: "Herald Island", area: "West Auckland" },
  { name: "Herne Bay", area: "Central Auckland" },
  { name: "Highbrook", area: "East Auckland" },
  { name: "Highland Park", area: "East Auckland" },
  { name: "Hillcrest", area: "North Shore" },
  { name: "Hillpark", area: "South Auckland" },
  { name: "Hillsborough", area: "Central Auckland" },
  { name: "Hingaia", area: "South Auckland" },
  { name: "Hobsonville", area: "West Auckland" },
  { name: "Homai", area: "South Auckland" },
  { name: "Howick", area: "East Auckland" },
  { name: "Huapai" },
  { name: "Huntington Park", area: "East Auckland" },
  { name: "Hūnua" },
  { name: "Kaipara Flats" },
  { name: "Kaitoke Beach" },
  { name: "Karaka" },
  { name: "Karekare" },
  { name: "Kaukapakapa" },
  { name: "Kaurilands", area: "West Auckland" },
  { name: "Kawakawa Bay" },
  { name: "Kawau Island" },
  { name: "Kelston", area: "West Auckland" },
  { name: "Kingseat" },
  { name: "Kingsland", area: "Central Auckland" },
  { name: "Kohimarama", area: "Central Auckland" },
  { name: "Konini", area: "West Auckland" },
  { name: "Kumeū" },
  { name: "Laingholm", area: "West Auckland" },
  { name: "Leigh" },
  { name: "Lincoln", area: "West Auckland" },
  { name: "Little Huia" },
  { name: "Little Manly Beach" },
  { name: "Long Bay", area: "East Coast Bays" },
  { name: "Lynfield", area: "Central Auckland" },
  { name: "Mahurangi Peninsula" },
  { name: "Mahurangi West" },
  { name: "Mairangi Bay", area: "East Coast Bays" },
  { name: "Manly" },
  { name: "Manukau Central", area: "South Auckland" },
  { name: "Manurewa", area: "South Auckland" },
  { name: "Maraetai" },
  { name: "Massey", area: "West Auckland" },
  { name: "Matakana" },
  { name: "Matakatia" },
  { name: "Matakatia Bay" },
  { name: "Mathesons Bay" },
  { name: "Matiatia" },
  { name: "Mauku" },
  { name: "McLaren Park", area: "West Auckland" },
  { name: "Meadowbank", area: "Central Auckland" },
  { name: "Medlands Beach" },
  { name: "Mellons Bay", area: "East Auckland" },
  { name: "Middlemore", area: "South Auckland" },
  { name: "Milford", area: "North Shore" },
  { name: "Milldale" },
  { name: "Millwater" },
  { name: "Mission Bay", area: "Central Auckland" },
  { name: "Mission Heights", area: "East Auckland" },
  { name: "Morningside", area: "Central Auckland" },
  { name: "Motairehe" },
  { name: "Motutapu Island" },
  { name: "Mount Albert", area: "Central Auckland" },
  { name: "Mount Eden", area: "Central Auckland" },
  { name: "Mount Roskill", area: "Central Auckland" },
  { name: "Mount Wellington", area: "Central Auckland" },
  { name: "Muriwai" },
  { name: "Murrays Bay", area: "East Coast Bays" },
  { name: "Māngere", area: "South Auckland" },
  { name: "Māngere Bridge", area: "South Auckland" },
  { name: "Māngere East", area: "South Auckland" },
  { name: "Narrow Neck", area: "North Shore" },
  { name: "New Lynn", area: "West Auckland" },
  { name: "New Windsor", area: "West Auckland" },
  { name: "Newmarket", area: "Central Auckland" },
  { name: "Newton", area: "Central Auckland" },
  { name: "Northcote", area: "North Shore" },
  { name: "Northcross", area: "North Shore" },
  { name: "Northpark", area: "East Auckland" },
  { name: "Okupu" },
  { name: "Omaha Cove" },
  { name: "One Tree Hill", area: "Central Auckland" },
  { name: "Onehunga", area: "Central Auckland" },
  { name: "Oneroa" },
  { name: "Onetangi" },
  { name: "Oranga", area: "Central Auckland" },
  { name: "Orapiu" },
  { name: "Oratia", area: "West Auckland" },
  { name: "Orewa" },
  { name: "Ostend" },
  { name: "Oteha", area: "North Shore" },
  { name: "Paerata" },
  { name: "Pahurehure", area: "South Auckland" },
  { name: "Pakatoa Island" },
  { name: "Pakuranga", area: "East Auckland" },
  { name: "Pakuranga Heights", area: "East Auckland" },
  { name: "Palm Beach" },
  { name: "Palmers Beach" },
  { name: "Panmure", area: "Central Auckland" },
  { name: "Papakura", area: "South Auckland" },
  { name: "Papatoetoe", area: "South Auckland" },
  { name: "Parakai" },
  { name: "Parau" },
  { name: "Parnell", area: "Central Auckland" },
  { name: "Patumāhoe" },
  { name: "Penrose", area: "Central Auckland" },
  { name: "Piha" },
  { name: "Pinehill", area: "North Shore" },
  { name: "Point Chevalier", area: "Central Auckland" },
  { name: "Point England", area: "Central Auckland" },
  { name: "Point Wells" },
  { name: "Pollok" },
  { name: "Ponsonby", area: "Central Auckland" },
  { name: "Ponui Island" },
  { name: "Port Albert" },
  { name: "Port Fitzroy" },
  { name: "Puhoi" },
  { name: "Pukekohe" },
  { name: "Puni" },
  { name: "Pākiri" },
  { name: "Pāremoremo" },
  { name: "Pōhuehue" },
  { name: "Ramarama" },
  { name: "Randwick Park", area: "South Auckland" },
  { name: "Red Beach" },
  { name: "Red Hill", area: "South Auckland" },
  { name: "Redvale" },
  { name: "Remuera", area: "Central Auckland" },
  { name: "Riverhead" },
  { name: "Rosebank", area: "West Auckland" },
  { name: "Rosedale", area: "North Shore" },
  { name: "Rosehill", area: "South Auckland" },
  { name: "Rothesay Bay", area: "East Coast Bays" },
  { name: "Royal Heights", area: "West Auckland" },
  { name: "Royal Oak", area: "Central Auckland" },
  { name: "Rākino Island" },
  { name: "Rānui", area: "West Auckland" },
  { name: "Saint Heliers", area: "Central Auckland" },
  { name: "Saint Marys Bay", area: "Central Auckland" },
  { name: "Sandringham", area: "Central Auckland" },
  { name: "Sandspit" },
  { name: "Schnapper Rock", area: "North Shore" },
  { name: "Scotts Landing" },
  { name: "Shamrock Park", area: "East Auckland" },
  { name: "Shelly Beach" },
  { name: "Shelly Park", area: "East Auckland" },
  { name: "Silverdale" },
  { name: "Snells Beach" },
  { name: "Somerville", area: "East Auckland" },
  { name: "Southdown", area: "Central Auckland" },
  { name: "St Johns", area: "Central Auckland" },
  { name: "St Lukes", area: "Central Auckland" },
  { name: "Stanley Point", area: "North Shore" },
  { name: "Stanmore Bay" },
  { name: "Stillwater" },
  { name: "Stonefields", area: "Central Auckland" },
  { name: "Sunnyhills", area: "East Auckland" },
  { name: "Sunnynook", area: "North Shore" },
  { name: "Sunnyvale", area: "West Auckland" },
  { name: "Surfdale" },
  { name: "Swanson", area: "West Auckland" },
  { name: "Takanini", area: "South Auckland" },
  { name: "Takapuna", area: "North Shore" },
  { name: "Tauhoa" },
  { name: "Taupaki" },
  { name: "Te Atatū Peninsula", area: "West Auckland" },
  { name: "Te Atatū South", area: "West Auckland" },
  { name: "Te Hana" },
  { name: "Te Henga / Bethells Beach" },
  { name: "Te Papapa", area: "Central Auckland" },
  { name: "Te Ārai" },
  { name: "The Gardens", area: "South Auckland" },
  { name: "Three Kings", area: "Central Auckland" },
  { name: "Ti Point" },
  { name: "Tindalls Beach" },
  { name: "Tiritiri Matangi Island" },
  { name: "Titirangi", area: "West Auckland" },
  { name: "Tomarata" },
  { name: "Torbay", area: "East Coast Bays" },
  { name: "Totara Heights", area: "South Auckland" },
  { name: "Tryphena" },
  { name: "Tāmaki", area: "Central Auckland" },
  { name: "Tāpora" },
  { name: "Tāwharanui Peninsula" },
  { name: "Tōtara Vale", area: "North Shore" },
  { name: "Unsworth Heights", area: "North Shore" },
  { name: "Wai o Taiki Bay", area: "Central Auckland" },
  { name: "Waiake", area: "East Coast Bays" },
  { name: "Waiatarua" },
  { name: "Waiau Pā" },
  { name: "Waiheke Island" },
  { name: "Waikoukou Valley" },
  { name: "Waikōwhai", area: "Central Auckland" },
  { name: "Waima", area: "West Auckland" },
  { name: "Waimauku" },
  { name: "Wainui" },
  { name: "Waioneke" },
  { name: "Waipatukahu" },
  { name: "Waipipi" },
  { name: "Wairau Valley", area: "North Shore" },
  { name: "Waitoki" },
  { name: "Waitākere" },
  { name: "Waiuku" },
  { name: "Waiwera" },
  { name: "Warkworth" },
  { name: "Waterview", area: "Central Auckland" },
  { name: "Wattle Downs", area: "South Auckland" },
  { name: "Weiti Village" },
  { name: "Wellsford" },
  { name: "Wesley", area: "Central Auckland" },
  { name: "West Harbour", area: "West Auckland" },
  { name: "Western Heights", area: "West Auckland" },
  { name: "Western Springs", area: "Central Auckland" },
  { name: "Westfield", area: "Central Auckland" },
  { name: "Westgate", area: "West Auckland" },
  { name: "Westmere", area: "Central Auckland" },
  { name: "Weymouth", area: "South Auckland" },
  { name: "Whangaparapara" },
  { name: "Whangaparāoa Peninsula" },
  { name: "Whangateau" },
  { name: "Whenuapai", area: "West Auckland" },
  { name: "Whitford" },
  { name: "Windsor Park", area: "North Shore" },
  { name: "Wiri", area: "South Auckland" },
  { name: "Woodcocks" },
  { name: "Woodhill" },
  { name: "Woodlands Park", area: "West Auckland" },
  { name: "Ōkiwi" },
  { name: "Ōkura" },
  { name: "Ōmaha" },
  { name: "Ōmiha" },
  { name: "Ōpaheke", area: "South Auckland" },
  { name: "Ōrere Point" },
  { name: "Ōrua Bay" },
  { name: "Ōrākei", area: "Central Auckland" },
  { name: "Ōtara", area: "South Auckland" },
  { name: "Ōtāhuhu", area: "South Auckland" },
  { name: "Ōwairaka", area: "Central Auckland" },
]

/** Lowercase, strip macrons and punctuation, and fold "St" / "Saint". */
export function normaliseSuburb(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\bsaint\b/g, 'st')
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Best matches for what has been typed, most relevant first:
 * whole-name prefix, then word prefix, then anywhere in the name.
 */
export function matchSuburbs(query: string, limit = 8): readonly Suburb[] {
  const q = normaliseSuburb(query)
  if (q.length < 2) return []

  // Hide the list once the exact name has been entered — but compare the
  // raw text, not the normalised form, so typing "kumeu" or "otahuhu"
  // still offers the correctly spelled "Kumeū" / "Ōtāhuhu" to pick.
  const typed = query.trim()

  const scored: { suburb: Suburb; score: number }[] = []
  for (const suburb of aucklandSuburbs) {
    const name = normaliseSuburb(suburb.name)
    if (suburb.name === typed) continue
    if (name.startsWith(q)) scored.push({ suburb, score: 0 })
    else if (name.split(' ').some((word) => word.startsWith(q))) scored.push({ suburb, score: 1 })
    else if (name.includes(q)) scored.push({ suburb, score: 2 })
  }

  scored.sort((a, b) => a.score - b.score || a.suburb.name.localeCompare(b.suburb.name))
  return scored.slice(0, limit).map((s) => s.suburb)
}
